exclude: 'docs|.git|.github|.tox|.idea|.vscode'
default_stages: [ commit ]

repos:
    -   repo: https://github.com/Lucas-C/pre-commit-hooks
        rev: v1.1.9
        hooks:
            -   id: forbid-crlf
            -   id: remove-crlf
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.4.0
        hooks:
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-merge-conflict
            -   id: check-yaml
                args: [ --unsafe ]
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v5.8.0
        hooks:
            -   id: isort
                args: [ "--profile", "black", "--filter-files" ]

    -   repo: https://github.com/ambv/black
        rev: 21.5b1
        hooks:
            -   id: black
                args: [ --config=pyproject.toml ]
    -   repo: https://github.com/pycqa/flake8
        rev: 3.9.2
        hooks:
            -   id: flake8
                args: [ '--config=setup.cfg' ]
                additional_dependencies: [ flake8-isort, flake8-typing-imports]
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.901
        hooks:
            -   id: mypy
                exclude: tests/
                additional_dependencies:
                    - types-click
                    - types-requests
                    - types-python-dateutil
